name: App CI

on:
  push:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"
  pull_request:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"

jobs:
  # Build & Test
  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      #  with:
      #    token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      # pnpm cache
      #- uses: actions/cache@v2
      #  with:
      #    path: ~/.pnpm-store
      #    key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      #    restore-keys: |
      #      ${{ runner.os }}-
      # Install
      - name: INSTALL
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2
          run_install: true

      # Build
      - name: BUILD
        run: pnpm build:ci

      # Test
      - name: TEST
        run: pnpm test:ci

      # Upload dist artifacts
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: dist
      #    path: dist/

      # Upload coverage artifacts
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: coverage
      #    path: coverage/lcov.info
